
---
- name: webapp playbook
  hosts: webapp
  remote_user: sysadmin
  become: yes
  become_user: root
  become_method: sudo
  tasks:
          - name: Get stat of directory php-fpm.d
            stat:
              path: /etc/php-fpm.d/
            register: check_owner
          - name: Show infor php-fpm.d
            debug:
              msg:
                  - "Owner: {{ check_owner.stat.pw_name }}"
                  - "Group: {{ check_owner.stat.gr_name }}"
                  - "Mode:  {{ check_owner.stat.mode }}"
          - name: Get stat of file /etc/php-fpm.d/www.conf
            stat:
              path: /etc/php-fpm.d/www.conf
            register: check_owner0
          - name: Show infor www.conf
            debug:
              msg:
                  - "Owner: {{ check_owner0.stat.pw_name }}"
                  - "Group: {{ check_owner0.stat.gr_name }}"
                  - "Mode:  {{ check_owner0.stat.mode }}"
          - name: Get stat of file php.ini
            stat:
              path: /etc/php.ini
            register: check_owner1
          - name: Show infor php.ini
            debug:
              msg:
                  - "Owner: {{ check_owner1.stat.pw_name }}"
                  - "Group: {{ check_owner1.stat.gr_name }}"
                  - "Mode:  {{ check_owner1.stat.mode }}"
          - name: Get stat of /var/log/php-fpm
            stat:
              path: /var/log/php-fpm
            register: check_owner2
          - name: Show infor /var/log/php-fpm
            debug:
              msg:
                  - "Owner: {{ check_owner2.stat.pw_name }}"
                  - "Group: {{ check_owner2.stat.gr_name }}"
                  - "Mode:  {{ check_owner2.stat.mode }}"         
          - name: Get stat of directory /var/www
            stat:
              path: /var/www
            register: check_owner3
          - name: Show infor of /var/www
            debug:
              msg:
                  - "Owner: {{ check_owner3.stat.pw_name }}"
                  - "Group: {{ check_owner3.stat.gr_name }}"
                  - "Mode:  {{ check_owner3.stat.mode }}"
          - name: Get stat of directory /var/www/html
            stat:
              path: /var/www/html
            register: check_owner4
          - name: Show infor of /var/www/html
            debug:
              msg:
                  - "Owner: {{ check_owner4.stat.pw_name }}"
                  - "Group: {{ check_owner4.stat.gr_name }}"
                  - "Mode:  {{ check_owner4.stat.mode }}"
          - name: Get stat of directory /var/log/nginx
            stat:
              path: /var/log/nginx
            register: check_owner5
          - name: Show infor of /var/log/nginx
            debug:
              msg:
                  - "Owner: {{ check_owner5.stat.pw_name }}"
                  - "Group: {{ check_owner5.stat.gr_name }}"
                  - "Mode:  {{ check_owner5.stat.mode }}"        
          - name: Get stat of file /etc/nginx/nginx.conf
            stat:
              path: /etc/nginx/nginx.conf
            register: check_owner6
          - name: Show infor of /etc/nginx/nginx.conf
            debug:
              msg:
                  - "Owner: {{ check_owner6.stat.pw_name }}"
                  - "Group: {{ check_owner6.stat.gr_name }}"
                  - "Mode:  {{ check_owner6.stat.mode }}"
          - name: Get stat of directory /usr/share/nginx/html
            stat:
              path: /usr/share/nginx/html
            register: check_owner7
          - name: Show infor of /usr/share/nginx/html
            debug:
              msg:
                  - "Owner: {{ check_owner7.stat.pw_name }}"
                  - "Group: {{ check_owner7.stat.gr_name }}"
                  - "Mode:  {{ check_owner7.stat.mode }}"
          - name: Get stat of directory /var/lib
            stat:
              path: /var/lib
            register: check_owner8
          - name: Show infor of /var/lib
            debug:
              msg:
                  - "Owner: {{ check_owner8.stat.pw_name }}"
                  - "Group: {{ check_owner8.stat.gr_name }}"
                  - "Mode:  {{ check_owner8.stat.mode }}"
          - name: Get stat of directory /var/lib64
            stat:
              path: /var/lib64
            register: check_owner9
          - name: Show infor of /var/lib64
            debug:
              msg:
                  - "Owner: {{ check_owner9.stat.pw_name }}"
                  - "Group: {{ check_owner9.stat.gr_name }}"
                  - "Mode:  {{ check_owner9.stat.mode }}"
          
          
                
         
                  
         



